<<<<<<< HEAD
# Generated by Django 3.1.3 on 2020-11-18 09:55
=======
# Generated by Django 3.1.2 on 2020-11-19 04:45
>>>>>>> b4f7691... [ADD] views.py 작성

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'auths',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=1000)),
                ('name_kor', models.CharField(max_length=50)),
                ('name_eng', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('rrn', models.CharField(max_length=1000, null=True)),
                ('mobile', models.CharField(max_length=50)),
                ('emergency_num', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=254)),
                ('personal_email', models.EmailField(max_length=254)),
                ('bank_name', models.CharField(max_length=50, null=True)),
                ('bank_account', models.CharField(max_length=1000, null=True)),
                ('passport_num', models.CharField(max_length=1000, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('detailed_address', models.CharField(max_length=200, null=True)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.auth')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField(null=True)),
                ('probation_period', models.CharField(max_length=50, null=True)),
                ('worked_since', models.DateField(null=True)),
                ('total_experience', models.CharField(max_length=50, null=True)),
                ('annual_vacation', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('promotion_date', models.DateField(null=True)),
                ('promoted_at', models.DateField(null=True)),
                ('pass_num', models.CharField(max_length=50, null=True)),
                ('etc', models.TextField(null=True)),
                ('annual_vacation_permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='employee.employee')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'db_table': 'employee_details',
            },
        ),
    ]
