# Generated by Django 3.1.3 on 2020-12-08 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'auths',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.CharField(max_length=500)),
                ('account', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=1000)),
                ('name_kor', models.CharField(max_length=50)),
                ('name_eng', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50, null=True)),
                ('rrn', models.CharField(max_length=1000)),
                ('mobile', models.CharField(max_length=50)),
                ('emergency_num', models.CharField(max_length=50, null=True)),
                ('company_email', models.EmailField(max_length=254, null=True)),
                ('personal_email', models.EmailField(max_length=254, null=True)),
                ('bank_name', models.CharField(max_length=50, null=True)),
                ('bank_account', models.CharField(max_length=1000, null=True)),
                ('passport_num', models.CharField(max_length=1000, null=True)),
                ('post_num', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('detailed_address', models.CharField(max_length=200, null=True)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.auth')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
