# Generated by Django 3.1.2 on 2020-11-19 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'dates',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'labels',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('description', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('amended_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule_amended_employee', to='employee.employee')),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='ScheduleParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
            ],
            options={
                'db_table': 'schedule_participants',
            },
        ),
        migrations.CreateModel(
            name='ScheduleDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.date')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
            ],
            options={
                'db_table': 'schedule_dates',
            },
        ),
        migrations.CreateModel(
            name='ScheduleAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=500)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
            ],
            options={
                'db_table': 'schedule_attachments',
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.ManyToManyField(through='schedule.ScheduleDate', to='schedule.Date'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.label'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='participant',
            field=models.ManyToManyField(related_name='schedule_employee', through='schedule.ScheduleParticipant', to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='written_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule_wrote_employee', to='employee.employee'),
        ),
    ]
