# Generated by Django 3.1.2 on 2020-11-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='begin_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='finish_at',
            field=models.DateTimeField(),
        ),
    ]
