# Generated by Django 3.1.2 on 2020-12-01 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20201130_1047'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='participant',
            field=models.ManyToManyField(through='schedule.ScheduleParticipant', to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='scheduleparticipant',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.schedule'),
        ),
    ]
