# Generated by Django 3.1.2 on 2020-11-21 06:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 21, 6, 42, 0, 898405, tzinfo=utc)),
        ),
    ]
