# Generated by Django 3.1.2 on 2020-12-01 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20201201_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleparticipant',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='schedule.schedule'),
        ),
    ]
