# Generated by Django 3.1.3 on 2020-12-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20201202_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticeattachment',
            old_name='file',
            new_name='url',
        ),
        migrations.AddField(
            model_name='noticeattachment',
            name='code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticeattachment',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticeattachment',
            name='size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
