# Generated by Django 3.1.3 on 2020-11-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectparticipant',
            name='is_liked',
        ),
        migrations.AddField(
            model_name='project',
            name='is_liked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
