# Generated by Django 3.1.3 on 2020-12-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20201201_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattachment',
            name='size',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectattachment',
            name='url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectattachment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
