# Generated by Django 3.1.3 on 2020-12-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20201207_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattachment',
            name='code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
