# Generated by Django 3.1.3 on 2020-12-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20201208_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='total_pause',
            field=models.DurationField(default=0),
        ),
    ]
