# Generated by Django 3.1.3 on 2020-12-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20201208_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='total_pause',
            field=models.IntegerField(default=0),
        ),
    ]
