# Generated by Django 3.1.3 on 2020-12-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20201208_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='total_pause',
            field=models.DurationField(default='0 00:00:00'),
        ),
    ]
